name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    environment: EC2_USER

    steps:
      - name: Deploy Frontend
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: |
            cd /home/ubuntu/mini-facebook
            git pull origin main

            cd client
            npm install
            npm run build

            pm2 restart vaaknow-frontend
            pm2 save