name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest

    environment: EC2_USER

    steps:
      - name: Deploy Backend
        uses: appleboy/ssh-action@v1.2.0

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_PORT }}

          script: |
            cd /home/ubuntu/mini-facebook
            git pull origin main

            cd server
            npm install

            pm2 restart vaaknow-backend --update-env
            pm2 save